server:
  port: 3333

spring:
  cloud:
    gateway:
      mvc:
        routes:
        - id: welcome-api
          uri: lb://WELCOME-API
          predicates:
          - Path=/welcome
        - id: greet-api
          uri: lb://TARGET-API
          predicates:
          - Path=/greet
        
  application:
    name: CLOUD-API-GATEWAY

